Revert "cpu_input_boost: Update SCREEN_AWAKE bit conditional"
This isn't for raphael I think?

    ../drivers/cpufreq/cpu_input_boost.c:303:16: error: use of undeclared identifier 'MSM_DRM_BLANK_UNBLANK_CUST'; did you mean 'MSM_DRM_BLANK_UNBLANK'?
            if (*blank == MSM_DRM_BLANK_UNBLANK_CUST) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                          MSM_DRM_BLANK_UNBLANK
    ../include/linux/msm_drm_notify.h:25:2: note: 'MSM_DRM_BLANK_UNBLANK' declared here
            MSM_DRM_BLANK_UNBLANK,
            ^
    1 error generated.

This reverts commit b4e705d60a637a4ba55fc7a57a3787cd087c5d14.

Signed-off-by: Wrdn28 <ifloraxd@gmail.com>