sched/core: remove unused variable `css` caused by "drop clamp input boosting"
../kernel/sched/core.c:978:30: error: unused variable 'css' [-Werror,-Wunused-variable]
        struct cgroup_subsys_state *css;
                                    ^
1 error generated.

Signed-off-by: Wrdn28 <ifloraxd@gmail.com>